function [Jx, Ju] = stateTransitionFcnJacobian(x, u, ~, ~, ~)
% This function was generated by MATLAB (Version 24.2).
% 15-Oct-2024 01:09:29
%# codegen
persistent ADdata
if isempty(ADdata)
    ADdata = coder.load('stateTransitionFcnJacobianADdata','constants');
end
[~,J] = stateTransitionFcnJacobianAD([x;u],ADdata.constants);
Jx = J(:,1:6);
Ju = J(:,[7 8]);
